name: Generate Charts

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 10 * * 1-5"   # run at 10:00 UTC, Mon-Fri (market days)

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      SHEET_ID: ${{ secrets.SHEET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install gspread oauth2client matplotlib pandas

      - name: Run chart generator
        run: python sheets_loader.py

      - name: Upload charts as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: output_charts/
