name: Update NIFTY Sheet

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 1 minute from 09:15–09:59 IST (03:45–03:59 UTC)
    - cron: "45-59/1 3 * * 1-5"

    # Runs every 1 minute from 10:00–15:30 IST (04:00–10:00 UTC)
    - cron: "*/1 4-10 * * 1-5"
    
  workflow_dispatch:
    inputs:
      run_code2:
        description: "Run experimental Code2 instead of Code1?"
        required: false
        default: "false"

jobs:
  code1:
    if: ${{ github.event.inputs.run_code2 != 'true' }}  # Run by default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas gspread oauth2client urllib3 pytz

      - name: Set up Google credentials
        run: |
          echo "${GOOGLE_CREDENTIALS}" > "$GITHUB_WORKSPACE/service_account.json"
          test -s "$GITHUB_WORKSPACE/service_account.json" || { echo "Credentials file is empty"; exit 1; }
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run update script (Code1)
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          POLLING_INTERVAL: 30
          GOOGLE_CREDENTIALS_PATH: ${{ github.workspace }}/service_account.json
        run: python NSE_Option_Chainonline.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: option_chain_updater1.log

  code2:
    if: ${{ github.event.inputs.run_code2 == 'true' }}  # Only run when manually selected
    runs-on: ubuntu-latest
    concurrency:
      group: nifty-update
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas gspread oauth2client urllib3 pytz

      - name: Set up Google credentials
        run: |
          echo "${GOOGLE_CREDENTIALS}" > "$GITHUB_WORKSPACE/service_account.json"
          test -s "$GITHUB_WORKSPACE/service_account.json" || { echo "Credentials file is empty"; exit 1; }
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run update script (Code2 with market check)
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          POLLING_INTERVAL: 30
          GOOGLE_CREDENTIALS_PATH: ${{ github.workspace }}/service_account.json
        run: |
          echo "Checking if market is open..."
          python - <<'EOF'
          import datetime, pytz, sys
          ist = pytz.timezone("Asia/Kolkata")
          now = datetime.datetime.now(ist).time()
          market_open = datetime.time(9, 15)
          market_close = datetime.time(15, 30)
          if not (market_open <= now <= market_close):
              print("Market is closed, exiting workflow.")
              sys.exit(0)
          EOF
          python NSE_Option_Chainonline.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: option_chain_updater1.log
