name: Update NIFTY Sheet

on:
  push:
    branches:
      - main
  schedule:
    # Run every 5 minutes 
    - cron: "*/5 6-18 * * 1-6"  # 3:40 AM to 6:20 PM UTC, all days
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas gspread oauth2client urllib3 pytz

      - name: Set up Google credentials
  run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account.json
  shell: bash

      - name: Run update script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDENTIALS_PATH: $GITHUB_WORKSPACE/service_account.json
          POLLING_INTERVAL: 30  # Match the script's default interval
        run: python NSE_Option_Chain.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: option_chain_updater.log
