name: Update NIFTY Sheet

on:
  push:
    branches:
      - main
  schedule:
    # Run every 1 minute from 9:15 AM to 4:20 PM IST (3:45 AM to 10:50 AM UTC)
    - cron: "*/1 9-19 * * 1-5"
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas gspread oauth2client urllib3 pytz

      - name: Set up Google credentials
        run: |
          echo "${GOOGLE_CREDENTIALS}" > "$GITHUB_WORKSPACE/service_account.json"
          test -s "$GITHUB_WORKSPACE/service_account.json" || { echo "Credentials file is empty"; exit 1; }
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run update script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          POLLING_INTERVAL: 30
          GOOGLE_CREDENTIALS_PATH: ${{ github.workspace }}/service_account.json
        run: python NSE_Option_Chainonline.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: option_chain_updater1.log
