name: Update NIFTY Sheet

on:
  push:
    branches:
      - main
  schedule:
    # Run every 5 minutes from 9:15 AM to 6:20 PM IST (3:45 AM to 12:50 PM UTC)
    - cron: "*/1 9-16 * * 1-6"
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas gspread oauth2client urllib3 pytz

      - name: Set up Google credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $GITHUB_WORKSPACE/service_account.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run update script
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          POLLING_INTERVAL: 30
          GOOGLE_CREDENTIALS_PATH: $GITHUB_WORKSPACE/service_account.json
        run: python NSE_Option_Chain.py  # Adjusted path

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: script-logs
          path: option_chain_updater.log  # Relative to $GITHUB_WORKSPACE
